## Задача 1
### 1.
Скачать данные по ссылке https://www.kaggle.com/datasets/ionaskel/laptop-prices
### 2.
Считать данные с помощью pandas
### 3.
Вывести на экран первые 5 строк

In [116]:
import pandas as pd
df = pd.read_csv('laptop_price.csv',encoding='cp1251')
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

### 4.
Создать новый признак Cpu_Company, который будет содержать только название фирмы, которая произвела CPU (Intel, AMD и т.д)

In [117]:
df['Cpu_Company'] = 0 # Создаем новый признак (колонку), который изначально пуст
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,0
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,0
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,0

In [118]:
df[['Cpu_Company', 'Cpu']] # внешние [] относятся к df, внутренние [] создают объект "список"

      Cpu_Company                                   Cpu
0               0                  Intel Core i5 2.3GHz
1               0                  Intel Core i5 1.8GHz
2               0            Intel Core i5 7200U 2.5GHz
3               0                  Intel Core i7 2.7GHz
4               0                  Intel Core i5 3.1GHz
...           ...                                   ...
1298            0            Intel Core i7 6500U 2.5GHz
1299            0            Intel Core i7 6500U 2.5GHz
1300            0  Intel Celeron Dual Core N3050 1.6GHz
1301            0            Intel Core i7 6500U 2.5GHz
1302            0  Intel Celeron Dual Core N3050 1.6GHz

[1303 rows x 2 columns]

In [119]:
def decompos_str (strcpu): # Создаем функцию, чтобы создать обработчик, который будет обрабатывать каждую ячейку колонки Cpu. Нужно сделать декомпозицию, вычленить str до пробела
    return strcpu.split()[0]
df['Cpu_Company'] = df['Cpu'].apply(decompos_str)
df[['Cpu','Cpu_Company']]

                                       Cpu Cpu_Company
0                     Intel Core i5 2.3GHz       Intel
1                     Intel Core i5 1.8GHz       Intel
2               Intel Core i5 7200U 2.5GHz       Intel
3                     Intel Core i7 2.7GHz       Intel
4                     Intel Core i5 3.1GHz       Intel
...                                    ...         ...
1298            Intel Core i7 6500U 2.5GHz       Intel
1299            Intel Core i7 6500U 2.5GHz       Intel
1300  Intel Celeron Dual Core N3050 1.6GHz       Intel
1301            Intel Core i7 6500U 2.5GHz       Intel
1302  Intel Celeron Dual Core N3050 1.6GHz       Intel

[1303 rows x 2 columns]

In [120]:
df['Cpu_Company'].value_counts() # Сгруппировали все значения CPU_Company, так можем проверить, допустили ли ошибку в функции

Cpu_Company
Intel      1240
AMD          62
Samsung       1
Name: count, dtype: int64

### 5.
Создать новый признак Memory_Amount, который будет содержать только количество Gb памяти без указания типа носителя (128, 1024, 256 и т.д.)

In [121]:
df['Memory_Amount'] = 0 # Создаем новый признак (колонку), который изначально пуст
df['Memory'].value_counts() # ознакомимся, в какой состоянии столбец Memory, чтобы понять, какой способо извлечения данных подойдет

Memory
256GB SSD                        412
1TB HDD                          223
500GB HDD                        132
512GB SSD                        118
128GB SSD +  1TB HDD              94
128GB SSD                         76
256GB SSD +  1TB HDD              73
32GB Flash Storage                38
2TB HDD                           16
64GB Flash Storage                15
512GB SSD +  1TB HDD              14
1TB SSD                           14
256GB SSD +  2TB HDD              10
1.0TB Hybrid                       9
256GB Flash Storage                8
16GB Flash Storage                 7
32GB SSD                           6
180GB SSD                          5
128GB Flash Storage                4
512GB SSD +  2TB HDD               3
16GB SSD                           3
512GB Flash Storage                2
1TB SSD +  1TB HDD                 2
256GB SSD +  500GB HDD             2
128GB SSD +  2TB HDD               2
256GB SSD +  256GB SSD             2
512GB SSD +  256GB SSD             1
512GB SSD +  512GB SSD             1
64GB Flash Storage +  1TB HDD      1
1TB HDD +  1TB HDD                 1
32GB HDD                           1
64GB SSD                           1
128GB HDD                          1
240GB SSD                          1
8GB SSD                            1
508GB Hybrid                       1
1.0TB HDD                          1
512GB SSD +  1.0TB Hybrid          1
256GB SSD +  1.0TB Hybrid          1
Name: count, dtype: int64

In [122]:
def decompos_mem(str_mem): 
    # Сначала создаем функцию, которая не будет учитывать терабайты. 
    # Split до пробела: str_mem.split()[0]
    # а потом срезом удаляем  буквенные обозначения памяти (GB, TB) до -2 индекса: str_mem.split()[0][:-2]
    # преобразуем строку в INT, вызываем функцию int(): int(str_mem.split()[0][:-2])
    return int(float((str_mem.split()[0][:-2]))) #добавляем возможность делать из вещественного числа целое. сначала выражение преобразуем в float, потом в int

In [123]:
# ячейка тестирования def decompos_mem
decompos_mem('1TB HDD ')

1

In [124]:
# ячейка тестирования def decompos_mem
decompos_mem('256GB SSD +  1.0TB Hybrid  ')

256

In [125]:
# ячейка тестирования def decompos_mem
decompos_mem('1.0TB HDD')

1

In [126]:
df['Memory_Amount'] = df['Memory'].apply(decompos_mem) # подставляем decompos_mem в формирование столбца Memory_Amount

In [127]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256

### 6.
Создать новый признак Memory_Type, который будет содержать только тип носителя (HDD, SDD и т.д.)

In [128]:
def decompos_type(str_type): # создаем функцию
    return str_type.split()[1]

df['Memory_Type'] = df['Memory'].apply(decompos_type) # подставляем decompos_type в формирование столбца Memory_Type

decompos_type('256GB SSD +  1.0TB Hybrid  ') # тестируем на строке

'SSD'

In [129]:
df.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

In [130]:
df['Memory_Type'].value_counts()

Memory_Type
SSD       843
HDD       375
Flash      75
Hybrid     10
Name: count, dtype: int64

### 7.
Удалите признаки Memory и ScreenResolution

In [131]:
df.drop(columns=['Memory', 'ScreenResolution']) # в таком варианте drop не меняет dataframe, а создает новый (страый остался неизменным, с этими колонками)

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Intel Core i7 6500U 2.5GHz,4GB,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Intel,128,SSD
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Intel,512,SSD
1300,1318,Lenovo,IdeaPad 100S-14IBR,Notebook,14.0,Intel Celeron Dual Core N3050 1.6GHz,2GB,Intel HD Graphics,Windows 10,1.5kg,229.00,Intel,64,Flash
1301,1319,HP,15-AC110nv (i7-6500U/6GB/1TB/Radeon,Notebook,15.6,Intel Core i7 6500U 2.5GHz,6GB,AMD Radeon R5 M330,Windows 10,2.19kg,764.00,Intel,1,HDD
1302,1320,Asus,X553SA-XX031T (N3050/4GB/500GB/W10),Notebook,15.6,Intel Celeron Dual Core N3050 1.6GHz,4GB,Intel HD Graphics,Windows 10,2.2kg,369.00,Intel,500,HDD

In [132]:
# Еще способ: можно переопределить данные: df = df.drop(columns=['Memory', 'ScreenResolution']) - лучше не использовать
df.drop(columns=['Memory', 'ScreenResolution'], inplace=True) # Прописывая inplace=True указываем, что изменения должны произойти в старом dataframe
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD

## Задача 2
### 1. 
Создайте признак SSD, который изначально равен 0

In [133]:
df['SSD'] = 0
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0

### 2. 
Поставьте в признаке SSD 1, если ноутбук действительно с типом носителя SSD

In [134]:
df[df['Memory_Type'] == 'SSD'] # Присваиваем dataframe булеву маску

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,0
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,0
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,0
8,9,Asus,ZenBook UX430UN,Ultrabook,14.0,Intel Core i7 8550U 1.8GHz,16GB,Nvidia GeForce MX150,Windows 10,1.3kg,1495.00,Intel,512,SSD,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1284,1302,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Intel Core i7 6500U 2.5GHz,4GB,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Intel,128,SSD,0
1285,1303,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Intel,512,SSD,0
1289,1307,Asus,ZenBook UX305CA-UBM1,Ultrabook,13.3,Intel Core M 6Y30 0.9GHz,8GB,Intel HD Graphics 515,Windows 10,1.2kg,729.00,Intel,512,SSD,0
1298,1316,Lenovo,Yoga 500-14ISK,2 in 1 Convertible,14.0,Intel Core i7 6500U 2.5GHz,4GB,Intel HD Graphics 520,Windows 10,1.8kg,638.00,Intel,128,SSD,0
1299,1317,Lenovo,Yoga 900-13ISK,2 in 1 Convertible,13.3,Intel Core i7 6500U 2.5GHz,16GB,Intel HD Graphics 520,Windows 10,1.3kg,1499.00,Intel,512,SSD,0

In [135]:
#df.loc.df[df['Memory_Type'] == 'SSD', "SSD"] = 1
df.loc[df['Memory_Type'] == "SSD", 'SSD'] = 1 # в df.loc передаем булеву маску и столбец SSD. loc нужен, потому что мы меняем не все данные, а только отфильтрованные
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69,Intel,128,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34kg,898.94,Intel,128,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86kg,575.00,Intel,256,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83kg,2537.45,Intel,512,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60,Intel,256,SSD,1

### 3. 
Уберите в признаке Weight значения 'kg' и поменяйте его тип данных на вещественный

In [136]:
def decompos_weight(str_weight): # создаем функцию
    return float(str_weight.split()[0][:-2])

df['Weight'] = df['Weight'].apply(decompos_weight) # подставляем decompos_weight в формирование столбца Weight

decompos_weight('1.37kg') # тестируем на строке

1.37

## Задача 3
Создайте датафрейм с клиентами
laptop_id - это индексы датафрейма с ноутбуками

In [137]:
clients = pd.DataFrame({
    'client_id': [45, 32, 67, 33, 43],
    'laptop_id': [506, 398, 710, 120, 1999]
})
df.head()

,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
0,1,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 2.3GHz,8GB,Intel Iris Plus Graphics 640,macOS,1.37,1339.69,Intel,128,SSD,1
1,2,Apple,Macbook Air,Ultrabook,13.3,Intel Core i5 1.8GHz,8GB,Intel HD Graphics 6000,macOS,1.34,898.94,Intel,128,Flash,0
2,3,HP,250 G6,Notebook,15.6,Intel Core i5 7200U 2.5GHz,8GB,Intel HD Graphics 620,No OS,1.86,575.00,Intel,256,SSD,1
3,4,Apple,MacBook Pro,Ultrabook,15.4,Intel Core i7 2.7GHz,16GB,AMD Radeon Pro 455,macOS,1.83,2537.45,Intel,512,SSD,1
4,5,Apple,MacBook Pro,Ultrabook,13.3,Intel Core i5 3.1GHz,8GB,Intel Iris Plus Graphics 650,macOS,1.37,1803.60,Intel,256,SSD,1

### 1.
Присоедините к таблице clients данные по ноутбукам через метод join

In [138]:
clients_id = clients.set_index('laptop_id') # Для слияния сопоставление таблиц будет по индексам. В табличке clients устанваливаем индексы, чтобы потом соотнести. Метод set_index(имя_признака_который_будет_индексом)

In [139]:
clients_id.join(df) # Через метод join() передаем df

,client_id,laptop_ID,Company,Product,TypeName,Inches,Cpu,Ram,Gpu,OpSys,Weight,Price_euros,Cpu_Company,Memory_Amount,Memory_Type,SSD
laptop_id,,,,,,,,,,,,,,,,
506,45,513.0,Asus,ZenBook UX510UX-CN211T,Notebook,15.6,Intel Core i7 7500U 2.7GHz,8GB,Intel HD Graphics 620,Windows 10,2.00,1224.0,Intel,256.0,SSD,1.0
398,32,405.0,Dell,Precision M5520,Workstation,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia Quadro M1200,Windows 10,1.78,2712.0,Intel,256.0,SSD,1.0
710,67,718.0,Lenovo,Legion Y520-15IKBN,Gaming,15.6,Intel Core i7 7700HQ 2.8GHz,8GB,Nvidia GeForce GTX 1050 Ti,Windows 10,2.50,1249.0,Intel,128.0,SSD,1.0
120,33,123.0,Acer,Spin 3,Notebook,15.6,Intel Core i3 7100U 2.4GHz,6GB,Intel HD Graphics 620,Windows 10,2.10,479.0,Intel,1.0,HDD,0.0
1999,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
df.iloc[506] # слияние произошло по индексу!

laptop_ID                               513
Company                                Asus
Product              ZenBook UX510UX-CN211T
TypeName                           Notebook
Inches                                 15.6
Cpu              Intel Core i7 7500U 2.7GHz
Ram                                     8GB
Gpu                   Intel HD Graphics 620
OpSys                            Windows 10
Weight                                  2.0
Price_euros                          1224.0
Cpu_Company                           Intel
Memory_Amount                           256
Memory_Type                             SSD
SSD                                       1
Name: 506, dtype: object


### 2.
Присоедините к таблице clients данные по ноутбукам через метод merge. Это нужно, чтобы понимать, какие ноутбуки покупались клиентами

In [141]:
merged = clients.merge(df, left_on='laptop_id', right_on=df.index, how='left')
merged

TypeError: a bytes-like object is required, not 'RangeIndex'

## Задача 4
Составьте несколько сводных таблиц  (можно использовать Group By / pivot_table)
### 1.
Найдите среднюю стоимость ноутбуков в зависимости от компании производителя. Отсортируйте от меньшей стоимости к большей

In [ ]:
df.pivot_table(index='Company',values='Price_euros', aggfunc='mean').sort_values('Price_euros')

           Price_euros
Company
Vero        217.425000
Mediacom    295.000000
Chuwi       314.296667
Acer        626.775825
Fujitsu     729.000000
HP         1067.774854
Lenovo     1086.384444
Asus       1104.169367
Xiaomi     1133.462500
Dell       1186.068990
Toshiba    1267.812500
Samsung    1413.444444
Huawei     1424.000000
Apple      1564.198571
Microsoft  1612.308333
Google     1677.666667
MSI        1728.908148
LG         2099.000000
Razer      3346.142857

In [ ]:

df.pivot_table(index='Company',values='Price_euros', aggfunc=[min,max]) # можно передавать несколько функций

C:\Users\Елена\AppData\Local\Temp\ipykernel_6328\83782529.py:1: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.pivot_table(index='Company',values='Price_euros', aggfunc=[min,max])
C:\Users\Елена\AppData\Local\Temp\ipykernel_6328\83782529.py:1: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.pivot_table(index='Company',values='Price_euros', aggfunc=[min,max])

                  min         max
          Price_euros Price_euros
Company
Acer           174.00     2599.00
Apple          898.94     2858.00
Asus           191.90     3975.00
Chuwi          244.99      449.00
Dell           274.90     3659.40
Fujitsu        649.00      799.00
Google        1275.00     2199.00
HP             209.00     4389.00
Huawei        1349.00     1499.00
LG            1899.00     2299.00
Lenovo         229.00     4899.00
MSI            839.00     2799.00
Mediacom       239.00      389.00
Microsoft      989.00     2589.00
Razer         1029.00     6099.00
Samsung        269.00     1849.00
Toshiba        447.00     2799.00
Vero           196.00      260.00
Xiaomi         935.00     1399.95

### 2.
Найдите минимальную, среднюю и максимальную стоимости ноутбуков в зависимости от производителя процессора

In [144]:
import numpy as np
df.pivot_table(index='Cpu_Company',values='Price_euros', aggfunc=[min,max,np.mean])

C:\Users\Елена\AppData\Local\Temp\ipykernel_6328\406215192.py:2: FutureWarning: The provided callable <built-in function min> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df.pivot_table(index='Cpu_Company',values='Price_euros', aggfunc=[min,max,np.mean])
C:\Users\Елена\AppData\Local\Temp\ipykernel_6328\406215192.py:2: FutureWarning: The provided callable <built-in function max> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df.pivot_table(index='Cpu_Company',values='Price_euros', aggfunc=[min,max,np.mean])
C:\Users\Елена\AppData\Local\Temp\ipykernel_6328\406215192.py:2: FutureWarning: The provided callable <function mean at 0x0000003DC18A28E0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(index='Cpu_Company',values='Price_euros', aggfunc=[min,max,np.mean])

                    min         max         mean
            Price_euros Price_euros  Price_euros
Cpu_Company
AMD               199.0      2199.0   560.638871
Intel             174.0      6099.0  1152.214145
Samsung           659.0       659.0   659.000000

In [195]:
df.groupby('Cpu_Company').agg({'Price_euros': ['min','max','mean']}) # другой способ с помощью groupby

            Price_euros
                    min     max         mean
Cpu_Company
AMD               199.0  2199.0   560.638871
Intel             174.0  6099.0  1152.214145
Samsung           659.0   659.0   659.000000

### 3.
Постройте таблицу с подсчетом количества ноутбуков в данных в зависимости от производителя CPU и ОЗУ

In [193]:
df_pivot=df.pivot_table(index=['Cpu_Company', 'Ram'],values='Product', aggfunc='count')

df_pivot

                  Product
Cpu_Company Ram
AMD         12GB        2
            16GB        3
            2GB         1
            4GB        31
            6GB        13
            8GB        12
Intel       12GB       23
            16GB      197
            24GB        3
            2GB        21
            32GB       17
            4GB       343
            64GB        1
            6GB        28
            8GB       607
Samsung     4GB         1

### 4.
Постройте таблицу с подсчетом средней стоимости ноутбуков в данных в зависимости от операционной системы и GB памяти

In [158]:
df.pivot_table(index=['OpSys', 'Ram'],values='Price_euros', aggfunc=np.mean)

C:\Users\Елена\AppData\Local\Temp\ipykernel_6328\1470477035.py:1: FutureWarning: The provided callable <function mean at 0x0000003DC18A28E0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(index=['OpSys', 'Ram'],values='Price_euros', aggfunc=np.mean)

                   Price_euros
OpSys        Ram
Android      4GB    434.000000
Chrome OS    16GB  2199.000000
             2GB    234.333333
             4GB    397.726316
             8GB   1122.000000
Linux        12GB   949.000000
             16GB   974.000000
             4GB    417.705625
             8GB    814.618148
Mac OS X     16GB  2139.970000
             4GB    959.000000
             8GB   1167.333333
No OS        16GB  1265.316667
             4GB    393.980625
             8GB    722.674516
Windows 10   12GB  1205.998261
             16GB  1916.548315
             24GB  2206.333333
             2GB    257.534211
             32GB  3413.085882
             4GB    604.317509
             64GB  3975.000000
             6GB    615.206341
             8GB   1190.119217
Windows 10 S 16GB  2589.000000
             4GB    673.997500
             8GB   1668.950000
Windows 7    12GB  2299.000000
             16GB  2840.400000
             4GB   1036.020833
             8GB   1739.483704
macOS        16GB  2611.806667
             8GB   1490.978000

## Задача 5
Ответьте на несколько вопросов, используя методы группировки

### 1. 
Устройств каких компаний и с каким процессором больше?

In [196]:
pd.crosstab(index=df['Company'], columns=df['Cpu_Company']) # Признак из dataframe извлекаем через []

Cpu_Company  AMD  Intel  Samsung
Company
Acer          10     93        0
Apple          0     21        0
Asus          11    147        0
Chuwi          0      3        0
Dell           0    297        0
Fujitsu        0      3        0
Google         0      3        0
HP            25    249        0
Huawei         0      2        0
LG             0      3        0
Lenovo        16    281        0
MSI            0     54        0
Mediacom       0      7        0
Microsoft      0      6        0
Razer          0      7        0
Samsung        0      8        1
Toshiba        0     48        0
Vero           0      4        0
Xiaomi         0      4        0

In [197]:
pd.crosstab(index=df['Company'], columns=df['Cpu_Company'], normalize='columns') #  normalize='all',  normalize='columns'.  normalize='index' - высчитывает 100% от значений всей таблицы, колонок, строк

Cpu_Company       AMD     Intel  Samsung
Company
Acer         0.161290  0.075000      0.0
Apple        0.000000  0.016935      0.0
Asus         0.177419  0.118548      0.0
Chuwi        0.000000  0.002419      0.0
Dell         0.000000  0.239516      0.0
Fujitsu      0.000000  0.002419      0.0
Google       0.000000  0.002419      0.0
HP           0.403226  0.200806      0.0
Huawei       0.000000  0.001613      0.0
LG           0.000000  0.002419      0.0
Lenovo       0.258065  0.226613      0.0
MSI          0.000000  0.043548      0.0
Mediacom     0.000000  0.005645      0.0
Microsoft    0.000000  0.004839      0.0
Razer        0.000000  0.005645      0.0
Samsung      0.000000  0.006452      1.0
Toshiba      0.000000  0.038710      0.0
Vero         0.000000  0.003226      0.0
Xiaomi       0.000000  0.003226      0.0

### 2. 
С каким типом памяти и с каким объемом памяти больше устройств?

In [199]:
pd.crosstab(index=df['Memory_Amount'], columns=df['Memory_Type'])

Memory_Type    Flash  HDD  Hybrid  SSD
Memory_Amount
1                  0  225       9   16
2                  0   16       0    0
8                  0    0       0    1
16                 7    0       0    3
32                38    1       0    6
64                16    0       0    1
128                4    1       0  172
180                0    0       0    5
240                0    0       0    1
256                8    0       0  500
500                0  132       0    0
508                0    0       1    0
512                2    0       0  138